Master:
  InstallPlugins:
    - kubernetes:1.13.5
    - workflow-job:2.31
    - blueocean:1.9.0
    - slack:2.3
    - workflow-aggregator:2.6
    - credentials-binding:1.17
    - git:3.9.1
    - google-oauth-plugin:0.6
    - google-source-plugin:0.3
    - google-container-registry-auth:0.3
    - test-results-analyzer:0.3.5
  ServiceType: ClusterIP
Agent:
  Enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
Persistence:
  Size: 100Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins
